yarnPath: .yarn/releases/yarn-4.0.0.cjs
packageExtensions:
  axios@*:
    dependencies:
      debug: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  debug@*:
    dependencies:
      supports-color: '*'

nodeLinker: node-modules
