nodeLinker: node-modules

packageExtensions:
  axios@*:
    dependencies:
      debug: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
