packageExtensions:
  axios@*:
    dependencies:
      debug: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  debug@*:
    dependencies:
      supports-color: '*'

nodeLinker: node-modules
