version: 0.0
os: linux
files:

  - source: /
    destination: /home/ubuntu/deploy-front/
    overwrite: yes

permissions:

  - object: /home/ubuntu/deploy-front/
    pattern: "**"
    owner: root
    group: root
    mode: 777

hooks:
  ApplicationStop:

  - location: scripts/stop-fe.sh
    timeout: 60
    runas: root

  ApplicationStart:

  - location: scripts/start-fe.sh
    timeout: 60
    runas: root
