import React from 'react';

import NavBar from '@/app/(feed)/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <NavBar theme='light' />
      <div className='container mx-auto min-h-screen max-w-[1024px]'>
        {children}
      </div>
    </section>
  );
}
