name: Deploy to Argo CD

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ "*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # build job 완료 후 진행

    steps:
      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      # kustomize 명령을 가져온다.
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v3
        with:
          # kubernetes 설정정보 저장소
          repository: inje-megabrain/megabrain-infra-manager
          # 다른 저장소에 push 하려면 Personal Access Token이 필요.
          token: ${{ secrets.ARGOCD_ACTION_TOKEN }}

      # 새 이미지 버전으로 파일 수정
      - name: Update Kubernetes resources
        run: |
          cd apps/art-fe/
          kustomize edit set image jadru/artplatform-fe:${{ steps.image.outputs.version }}
          cat artfe.yaml

      # 수정된 파일 commit & push
      - name: Commit files
        run: |
          cd megabrain-infra-manager
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update image tag"
          git push -u origin deploy-argo
