name: Docker Image CI

on:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["*.*"]
  pull_request:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: jadru/artplatform-fe
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate Environment Variables File for Production
        run: |
          echo "NOTION_TOKEN=$NOTION_TOKEN" >> .env.production
          echo "NOTION_DATABASE_ID=$NOTION_DATABASE_ID" >> .env.production

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        run: echo "$DOCKER_REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile.production
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#  deploy:
#    name: CD on Argo CD
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Get verion
#        id: image
#        run: |
#          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
#          echo VERSION=$VERSION
#          echo "::set-output name=version::$VERSION"
#
#      # kustomize 명령을 가져온다.
#      - name: Setup Kustomize
#        uses: imranismail/setup-kustomize@v1
#
#      - name: Checkout kustomize repository
#        uses: actions/checkout@v3
#        with:
#          # kubernetes 설정정보 저장소
#          repository: inje-megabrain/megabrain-infra-manager
#          # 다른 저장소에 push 하려면 Personal Access Token이 필요.
#          token: ${{ secrets.ARGOCD_ACTION_TOKEN }}
#
#      # 새 이미지 버전으로 파일 수정
#      - name: Update Kubernetes resources
#        run: |
#          cd apps/art-fe/
#          kustomize edit.tsx set image jadru/artplatform-fe:${{ steps.image.outputs.version }}
#          cat kustomization.yaml
#
#      # 수정된 파일 commit & push
#      - name: Commit files
#        run: |
#          cd megabrain-infra-manager
#          git config --global user.email "github-actions@github.com"
#          git config --global user.name "github-actions"
#          git commit -am "Update image tag"
#          git push -u origin deploy-argo
